-- Test-only seed data for H2 (schema is generated by Hibernate).
-- Runs after Hibernate DDL thanks to defer-datasource-initialization.
-- JSON columns are stored as plain text strings in the test dialect.

INSERT INTO roles (id, name, role_type, description, is_active, created_at, updated_at) VALUES
  ('20000000-0000-0000-0000-000000000001', 'CONSUMER', 'consumer', 'Consumer', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('20000000-0000-0000-0000-000000000002', 'ADMIN', 'admin', 'Admin', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('20000000-0000-0000-0000-000000000003', 'COUNSELLOR', 'counsellor', 'Counsellor', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO questionnaires (id, code, title, description, is_default, is_active, version, question_ids, created_at, updated_at)
VALUES ('30000000-0000-0000-0000-000000000001', 'q_health_baseline', 'Health Baseline', 'Baseline', TRUE, TRUE, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO questions (id, questionnaire_id, question_key, text, question_type, options, question_order, is_required, is_active, validation_rules, created_at, updated_at) VALUES
  ('31000000-0000-0000-0000-000000000001', '30000000-0000-0000-0000-000000000001', 'age_group', 'Age group?', 'select', '["children","adults","seniors"]', 1, TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000002', '30000000-0000-0000-0000-000000000001', 'gender', 'Gender?', 'select', '["male","female","other"]', 2, TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000003', '30000000-0000-0000-0000-000000000001', 'weight_kg', 'Weight (kg)?', 'number', NULL, 3, TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000004', '30000000-0000-0000-0000-000000000001', 'height_cm', 'Height (cm)?', 'number', NULL, 4, TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000005', '30000000-0000-0000-0000-000000000001', 'activity_level', 'Activity?', 'select', '["sedentary","light","moderate","active","very_active"]', 5, TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000006', '30000000-0000-0000-0000-000000000001', 'health_goals', 'Goals?', 'multi_select', '["weight_loss","general_health","immunity"]', 6, TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000007', '30000000-0000-0000-0000-000000000001', 'dietary_preferences', 'Diet?', 'multi_select', '["vegetarian","balanced","high_protein"]', 7, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000008', '30000000-0000-0000-0000-000000000001', 'allergies', 'Allergies?', 'multi_select', '["peanuts","dairy","gluten","none"]', 8, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000009', '30000000-0000-0000-0000-000000000001', 'medical_conditions', 'Conditions?', 'multi_select', '["diabetes","hypertension","none"]', 9, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000010', '30000000-0000-0000-0000-000000000001', 'pregnant_or_nursing', 'Pregnant?', 'boolean', NULL, 10, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000011', '30000000-0000-0000-0000-000000000001', 'chronic_diseases', 'Chronic?', 'multi_select', '["diabetes","none"]', 11, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000012', '30000000-0000-0000-0000-000000000001', 'blood_group', 'Blood group?', 'select', '["A+","A-","B+","B-","AB+","AB-","O+","O-"]', 12, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000013', '30000000-0000-0000-0000-000000000001', 'sleep_hours', 'Sleep (h)?', 'number', NULL, 13, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000014', '30000000-0000-0000-0000-000000000001', 'stress_level', 'Stress?', 'select', '["low","moderate","high","very_high"]', 14, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000015', '30000000-0000-0000-0000-000000000001', 'smoker', 'Smoker?', 'boolean', NULL, 15, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('31000000-0000-0000-0000-000000000016', '30000000-0000-0000-0000-000000000001', 'alcohol', 'Alcohol?', 'boolean', NULL, 16, FALSE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO products (id, name, sku, category_code, category, age_group, status, description, allergens, dietary_tags, nutritional_info, created_at, updated_at) VALUES
  ('40000000-0000-0000-0000-000000000001', 'Whey Protein Isolate', 'SKU-0001', 'SPORTS', 'high', 'adults', 'ACTIVE', 'High protein', '["dairy"]', '["high_protein","muscle_gain","weight_gain"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000002', 'Daily Multi-Vitamin', 'SKU-0002', 'SUPPLEMENTS', 'medium', 'all', 'ACTIVE', 'Multivitamin', '[]', '["balanced","immunity","general_health"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000003', 'Omega-3 Fish Oil', 'SKU-0003', 'SUPPLEMENTS', 'medium', 'adults', 'ACTIVE', 'Omega 3', '["fish"]', '["general_health","heart_health"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000004', 'Low-Calorie Meal Replacement', 'SKU-0004', 'MEAL_REPLACEMENT', 'low', 'adults', 'ACTIVE', 'Weight management', '["dairy"]', '["low_calorie","weight_loss","balanced"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000005', 'Probiotic Digestive Support', 'SKU-0005', 'SUPPLEMENTS', 'medium', 'adults', 'ACTIVE', 'Digestive health', '[]', '["digestive_health","probiotic"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000006', 'Vitamin C Immunity Boost', 'SKU-0006', 'SUPPLEMENTS', 'medium', 'all', 'ACTIVE', 'Immunity', '[]', '["immunity","vitamin_c"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000007', 'High-Fiber Breakfast Cereal', 'SKU-0007', 'FOOD', 'medium', 'all', 'ACTIVE', 'Fiber cereal', '["gluten"]', '["digestive_health","balanced"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000008', 'Balanced Nutrition Shake', 'SKU-0008', 'MEAL_REPLACEMENT', 'medium', 'adults', 'ACTIVE', 'Balanced shake', '["soy"]', '["balanced","high_protein"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000009', 'Kids Calcium Chewables', 'SKU-0009', 'SUPPLEMENTS', 'medium', 'children', 'ACTIVE', 'Kids calcium', '[]', '["children","balanced"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('40000000-0000-0000-0000-000000000010', 'Senior Protein Blend', 'SKU-0010', 'SPORTS', 'high', 'seniors', 'ACTIVE', 'Senior protein', '["dairy"]', '["high_protein","seniors"]', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO product_rules (id, product_id, rule_definition, is_active, created_at, updated_at) VALUES
  ('50000000-0000-0000-0000-000000000001', '40000000-0000-0000-0000-000000000001', '{"not_for_age_groups":["children"],"allergens":["dairy"]}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('50000000-0000-0000-0000-000000000002', '40000000-0000-0000-0000-000000000004', '{"medical_exclusions":["diabetes"],"allergens":["dairy"]}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('50000000-0000-0000-0000-000000000003', '40000000-0000-0000-0000-000000000009', '{"not_for_age_groups":["adults","seniors"]}', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);